### ISSUE TITLE
Team management

### ISSUE THREAD

**Issue by Dpac99** [sinfo/deck2#261]
# Description
Create team management page

# Desired functionality
Should be able to manage existing teams, team members and other features. Should be able to add and edit teams on current event, with regards to name, members, etc..

**Comment by susmonteiro** [comment]
## ToDo
#### Right-bottom button, on teams page
- [ ] create new team

#### Pencil button (similar to member page)
- [ ] edit team (name)
- [ ] remove team

#### Speed dial on team page
- [ ] add member to team
- [ ] remove member from team

#### Member page
- [ ] edit member's team
